ConvertFrom-StringData -StringData @'
    error_missing_api_key = API key is missing. Please set the environment variable OPENAI_API_KEY or you can specify the parameter -api_key.
    error_missing_engine = Model is missing, Please set the environment variable OPENAI_API_MODEL or you can specify the parameter -model.
    error_missing_endpoint = Endpoint is missing, Please set the environment variable OPENAI_API_ENDPOINT or you can specify the parameter -endpoint.
    welcome = Welcome to OpenAI{0}'s world, The model you are currently using is: {1}, Please start with your prompt.
    shortcuts=Shortcuts：Press q (or bye) and Enter to exit, Press m and Enter to input multi-lines prompt， Press f and Enter to select a file from disk. please note, only Windows supports m and f mode.
    azure_version = (Azure)
    prompt = Prompt
    response = Answered as below, consumed tokes are : {0} = {1} + {2}
    multi_line_prompt = Please enter multiple lines of text
    cancel_button_message = You pressed the cancel button.
    multi_line_message = Your inputs are:
    file_prompt = Please select a file
    dialog_okbutton_text = Ok
    dialog_cancelbutton_text = Cancel
    update_prompt=We found new version of this module.`n`n{0}`n`nDo you want to update it now? [Y/N]
    update_success=Update successfully, please restart your PowerShell session.
    welcome_chatgpt = Welcome to ChatGPT {0}'s world, The model you are currently using is: {1}, Please start with your prompt.
    openai_unavaliable = You can't connect to openai service now, please check your network connection.
    powershell_version_unsupported = Only the Powershell core supports the stream parameter.
    verbose_prompt_local_file = Prompt is a local file path, read the file as prompt
    verbose_prompt_url = Prompt is a url, read the url as prompt
    verbose_prompt_lib = Prompt is a prompt library name, read the prompt from prompt library
    verbose_prompt_lib_gitee = Prompt library is gitee
    verbose_prompt_lib_notfound = Prompt library {0} not found
    verbose_parameters_received = Parameters received:`n {0}
    verbose_environment_received = Environment variables received:`n {0}
    verbose_parameters_parsed = Parameter parsed. api_key: {0}, model: {1}, endpoint: {2}
    verbose_context_received = Context received:`n {0}
    verbose_prompt_context_injected = Prompt after context injected: {0}
    verbose_prompt_mode = Prompt received: {0}, so it is in prompt mode, not in chat mode.
    verbose_prepare_params = Prepare the params for Invoke-WebRequest: `n {0}
    verbose_powershell_5_utf8 = Powershell 5 detected, use utf8 encoding
    verbose_response_utf8 = Response is utf8 encoded: {0}
    verbose_response_plain_text = Response parsed to plain text: {0}
    verbose_outfile_specified = Outfile is specified, write the response to the file: {0}
    verbose_outfile_not_specified = Outfile is not specified, write the response to the console
    verbose_chat_mode = Prompt not received, so it is in chat mode.
    verbose_chat_let_chat = Start a new loop - let's chat!
    verbose_chat_q_message = User pressed {0}, so we will quit the chat.
    verbose_chat_m_message = User pressed m, so we will prompt a window to collect user input in multi-lines mode.
    verbose_chat_m_message_not_supported = Multi-line input is not supported on this platform. Please use another platform or use the file mode.
    verbose_prompt_received = Prompt received: {0}
    verbose_chat_f_message = User pressed f, so we will prompt a window to collect user input from a file.
    verbose_chat_f_message_not_supported = File input is not supported on this platform. Please use another platform or use the file input mode.
    verbose_chat_file_read = File received: {0}
    verbose_prepare_messages = Prepare the messages: `n {0}
    verbose_chat_stream_mode = Stream mode detected, so we will use Invoke-WebRequest to stream the response.
    verbose_chat_stream_chunk_received = Chunk received: {0}
    verbose_chat_message_combined = Combined message:`n {0}
    verbose_chat_not_stream_mode = It is not in stream mode.
    verbose_chat_response_received = Response received:`n {0}
    verbose_chat_response_summary = Response parsed to plain text: {0}, total_tokens: {1}, prompt_tokens: {2}, completion_tokens: {3}
    verbose_image_parameter_parsed = Parameter parsed. api_key: {0}, endpoint: {1}
    verbose_image_download_completed = Image download completed, save the image to {0}
'@
