ConvertFrom-StringData -StringData @'
    error_missing_api_key = 缺少API密钥。请设置环境变量OPENAI_API_KEY，或者您可以指定参数-api_key。
    error_missing_engine = 缺少模型，请输入环境变量OPENAI_API_MODEL，或者您可以指定参数-model。
    error_missing_endpoint = 缺少端点，请输入环境变量OPENAI_API_ENDPOINT，或者您可以指定参数-endpoint。
    welcome = 欢迎来到OpenAI{0}的世界，您当前使用的模型是：{1}，请用您的提示开始。
    shortcuts=快捷键：按q（或bye）并按Enter键退出，按m并按Enter键输入多行提示，按f并按Enter键从磁盘选择文件。请注意，只有Windows支持m和f模式。
    azure_version = (Azure)
    prompt = 提示
    response = 如下回答，消耗的令牌是：{0} = {1} + {2}
    multi_line_prompt = 请输入多行文本
    cancel_button_message = 您按下了取消按钮。
    multi_line_message = 您的输入是：
    file_prompt = 请选择一个文件
    dialog_okbutton_text = 确定
    dialog_cancelbutton_text = 取消
    update_prompt=我们发现此模块的新版本。`n`n{0}`n`n您现在要更新吗？[Y/N]
    update_success=更新成功，请重新启动您的PowerShell会话。
    welcome_chatgpt = 欢迎来到ChatGPT {0}的世界，您当前使用的模型是：{1}，请用您的提示开始。
    openai_unavaliable = 您现在无法连接到openai服务，请检查您的网络连接。
    powershell_version_unsupported = 只有Powershell核心支持流参数。
    verbose_prompt_local_file = 提示是本地文件路径，将文件作为提示读取
    verbose_prompt_url = 提示是url，将url作为提示读取
    verbose_prompt_lib = 提示是提示库名称，从提示库中读取提示
    verbose_prompt_lib_gitee = 提示库是gitee
    verbose_prompt_lib_notfound = 提示库{0}未找到
    verbose_parameters_received = 收到的参数：`n {0}
    verbose_environment_received = 收到的环境变量：`n {0}
    verbose_parameters_parsed = 参数解析。api_key：{0}，model：{1}，endpoint：{2}
    verbose_context_received = 收到的上下文：`n {0}
    verbose_prompt_context_injected = 注入上下文后的提示：{0}
    verbose_prompt_mode = 收到的提示：{0}，因此它处于提示模式，而不是聊天模式。
    verbose_prepare_params = 为Invoke-WebRequest准备参数：`n {0}
    verbose_powershell_5_utf8 = 检测到Powershell 5，使用utf8编码
    verbose_response_utf8 = 响应是utf8编码：{0}
    verbose_response_plain_text = 响应解析为纯文本：{0}
    verbose_outfile_specified = 指定了Outfile，将响应写入文件：{0}
    verbose_outfile_not_specified = 未指定Outfile，将响应写入控制台
    verbose_chat_mode = 未收到提示，因此它处于聊天模式。
    verbose_chat_let_chat = 开始新循环 - 让我们聊天！
    verbose_chat_q_message = 用户按下了{0}，所以我们将退出聊天。
    verbose_chat_m_message = 用户按下了m，所以我们将提示一个窗口以在多行模式下收集用户输入。
    verbose_chat_m_message_not_supported = 此平台不支持多行输入。请使用另一个平台或使用文件模式。
    verbose_prompt_received = 收到的提示：{0}
    verbose_chat_f_message = 用户按下了f，所以我们将提示一个窗口以从文件中收集用户输入。
    verbose_chat_f_message_not_supported = 此平台不支持文件输入。请使用另一个平台或使用文件输入模式。
    verbose_chat_file_read = 收到的文件：{0}
    verbose_prepare_messages = 准备消息：`n {0}
    verbose_chat_stream_mode = 检测到流模式，因此我们将使用Invoke-WebRequest来流式传输响应。
    verbose_chat_stream_chunk_received = 收到的块：{0}
    verbose_chat_message_combined = 组合的消息：`n {0}
    verbose_chat_not_stream_mode = 它不在流模式中。
    verbose_chat_response_received = 收到的响应：`n {0}
    verbose_chat_response_summary = 响应解析为纯文本：{0}，total_tokens：{1}，prompt_tokens：{2}，completion_tokens：{3}
    verbose_image_parameter_parsed = 参数解析。api_key：{0}，endpoint：{1}
    verbose_image_download_completed = 图片下载完成，将图片保存到{0}
    thinking = 正在思考
    function_call = 正在调用工具
'@